# Generated by Django 5.0.1 on 2024-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizi',
            name='populer',
            field=models.BooleanField(default=False, verbose_name='Yeni Ve Populer Mi'),
        ),
    ]
