# Generated by Django 5.0.1 on 2024-01-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0007_category_dizi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dizi',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Dizi',
        ),
    ]
